config/routes.rb
Rails.application.routes.draw do
  get 'day_book/index'

  resources :calendar_bookings
  resources :shop_calendars
  resources :shop_stylist_workdays
  resources :shop_stylists
  resources :shop_workdays
  resources :shop_settings
  resources :shops
  resources :hair_dressers
  get 'booker/day'

  get 'booker/week'

  resources :bookings do
    collection do
      get 'make'
      post 'save'
    end
  end
  resources :services
  resources :clients
  resources :stylists
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  #  get 'store/index'
  # root 'day_book#index', as: 'day_book_index'


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :stylist
  belongs_to :client
  belongs_to :service
  has_many :calendar_bookings

  # testing
end

app/models/calendar_booking.rb
class CalendarBooking < ApplicationRecord
  belongs_to :booking
  belongs_to :shop_calendar
end

app/models/client.rb
class Client < ApplicationRecord
  belongs_to :stylist
  has_many :bookings
end

app/models/day_slot.rb
class ShopDayBook
  attr_accessor   :name
  attr_accessor   :day
  attr_accessor   :shop_id
  attr_accessor   :stylistdays
  attr_accessor   :shop
  def initialize (shop, day)
    @shop = shop
    @name = shop.name
    @day = day.to_s(:db)
    @shop_id = shop.id
    load_stylistdays(@day)
  end

  def load_stylistdays(day)
    @stylistdays = Array.new

    @shop.shop_stylists.each do |stylist|
      stylist_day = StylistDay.new(stylist, @day)
      @stylistdays.push(stylist_day)
    end

  end
end


class StylistDay
  attr_accessor :name
  attr_accessor :day
  attr_accessor :stylist_id
  attr_accessor :image_url
  attr_accessor :dayslots
  attr_accessor :stylist
  def initialize (stylist, day)
    @stylist = stylist
    @name = stylist.name
    @day = day.to_s
    @stylist_id = stylist_id
    @image_url = stylist.image_url
    load_slots()
  end
  def load_slots()
    start_date = DateTime.parse(@day).beginning_of_day.to_s(:db)
    end_date = DateTime.parse(@day).end_of_day.to_s(:db)
    search_str = "shop_id = "
    search_str += shop_id.to_s
    search_str += " AND stylist_id ="
    search_str += @stylist_id.to_s
    search_str += " AND slot_start >= Datetime('"
    search_str += start_date
    search_str += "') AND slot_end <= Datetime('"
    search_str += end_date + "')"
     #
    # load all the empty slots
    #
    @dayslots = Array.new
    last_id = 0
    ShopCalendar.where(search_str).find_each do |slot|
      #
      # if the slot is in the Calendar Bookings table, it means there is a booking for this slot
      #
      booking = CalendarBooking.find_by(shop_calendar_id:slot.id)
      if (booking) then
        if last_id == booking.booking_id then
          # ignore if we already created the booking slot
        else
          # create a new booking slot
          slot = CalendarSlot.new(booking.booking_id,"Booked")
          @dayslots.push(slot)
          last_id = booking.booking_id
        end
      else
        slot = CalendarSlot.new(slot.id,'Empty slot')
        @dayslots.push(slot)
      end
    end
  end
end


class CalendarSlot
  attr_accessor :slot_start
  attr_accessor :slot_id
  attr_accessor :duration
  attr_accessor :client_name
  attr_accessor :client_contact_no
  attr_accessor :client_id
  attr_accessor :service_name
  attr_accessor :slot_end
  attr_accessor :slot_type
  def initialize(slot_id, slot_type )
    @slot_type = slot_type
    @slot_id = slot_id
    if slot_type == "Empty slot" then
      slot = ShopCalendar.find(slot_id)
      @slot_start = slot.slot_start.to_s(:db)
      @duration = slot.duration
      @slot_end = slot.slot_end.to_s(:db)

    elsif slot_type == "Not Available" then


    elsif slot_type == "Booked" then
      slot = Booking.find(slot_id)
      client = slot.client
      service = slot.service
      @slot_start = slot.date.to_s(:db)
      @duration = service.duration
      @client_name = client.firstName + " " + client.lastName
      @client_contact_no = client.contactNo
      @client_id = client.id
      @service_name = service.name
      @slot_end = (slot.date + service.duration.minutes).to_s(:db)

    end


  end
end

app/models/hair_dresser.rb
class HairDresser < ApplicationRecord
  has_many :shops
end

app/models/service.rb
class Service < ApplicationRecord
  has_many :bookings
end

app/models/shop.rb
class Shop < ApplicationRecord
  belongs_to :hair_dresser
  has_many :shop_settings
  has_many :shop_workdays
  has_many :shop_calendars
  has_many :shop_stylists
  has_many :shop_stylist_workdays

end

app/models/shop_calendar.rb
class ShopCalendar < ApplicationRecord
  belongs_to :shop
  belongs_to :stylist
  has_many :calendar_bookings

end

app/models/shop_setting.rb
class ShopSetting < ApplicationRecord
  belongs_to :shop
end

app/models/shop_stylist.rb
class ShopStylist < ApplicationRecord
  belongs_to :shop
  belongs_to :stylist
end

app/models/shop_stylist_workday.rb
class ShopStylistWorkday < ApplicationRecord
  belongs_to :shop
  belongs_to :stylist
end

app/models/shop_workday.rb
class ShopWorkday < ApplicationRecord
  belongs_to :shop
end

app/models/stylist.rb
class Stylist < ApplicationRecord
  has_many :clients
  has_many :bookings
  has_many :shop_calendars
  has_many :shop_stylist_workdays
  has_many :shop_stylists

end

app/controllers/services_controller.rb
class ServicesController < ApplicationController
  before_action :set_service, only: [:show, :edit, :update, :destroy]

  # GET /services
  # GET /services.json
  def index
    @services = Service.all
  end

  # GET /services/1
  # GET /services/1.json
  def show
  end

  # GET /services/new
  def new
    @service = Service.new
  end

  # GET /services/1/edit
  def edit
  end

  # POST /services
  # POST /services.json
  def create
    @service = Service.new(service_params)

    respond_to do |format|
      if @service.save
        format.html { redirect_to @service, notice: 'Service was successfully created.' }
        format.json { render :show, status: :created, location: @service }
      else
        format.html { render :new }
        format.json { render json: @service.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /services/1
  # PATCH/PUT /services/1.json
  def update
    respond_to do |format|
      if @service.update(service_params)
        format.html { redirect_to @service, notice: 'Service was successfully updated.' }
        format.json { render :show, status: :ok, location: @service }
      else
        format.html { render :edit }
        format.json { render json: @service.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /services/1
  # DELETE /services/1.json
  def destroy
    @service.destroy
    respond_to do |format|
      format.html { redirect_to services_url, notice: 'Service was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_service
      @service = Service.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def service_params
      params.require(:service).permit(:name, :description, :duration, :price)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/booker_helper.rb
module BookerHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/day_book_helper.rb
module DayBookHelper
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/helpers/shops_helper.rb
module ShopsHelper
end

app/helpers/stylists_helper.rb
module StylistsHelper
end

app/views/services/_form.html.erb
<%= form_for(service) do |f| %>
  <% if service.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(service.errors.count, "error") %> prohibited this service from being saved:</h2>

      <ul>
      <% service.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>

  <div class="field">
    <%= f.label :duration %>
    <%= f.number_field :duration %>
  </div>

  <div class="field">
    <%= f.label :price %>
    <%= f.text_field :price %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/services/edit.html.erb
<h1>Editing Service</h1>

<%= render 'form', service: @service %>

<%= link_to 'Show', @service %> |
<%= link_to 'Back', services_path %>

app/views/services/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Services</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Duration</th>
      <th>Price</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @services.each do |service| %>
      <tr>
        <td><%= service.name %></td>
        <td><%= service.description %></td>
        <td><%= service.duration %></td>
        <td><%= service.price %></td>
        <td><%= link_to 'Show', service %></td>
        <td><%= link_to 'Edit', edit_service_path(service) %></td>
        <td><%= link_to 'Destroy', service, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Service', new_service_path %>

app/views/services/new.html.erb
<h1>New Service</h1>

<%= render 'form', service: @service %>

<%= link_to 'Back', services_path %>

app/views/services/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @service.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @service.description %>
</p>

<p>
  <strong>Duration:</strong>
  <%= @service.duration %>
</p>

<p>
  <strong>Price:</strong>
  <%= @service.price %>
</p>

<%= link_to 'Edit', edit_service_path(@service) %> |
<%= link_to 'Back', services_path %>