config/routes.rb
Rails.application.routes.draw do
  get 'day_book/index'

  resources :calendar_bookings
  resources :shop_calendars
  resources :shop_stylist_workdays
  resources :shop_stylists
  resources :shop_workdays
  resources :shop_settings
  resources :shops
  resources :hair_dressers
  get 'booker/day'

  get 'booker/week'

  resources :bookings do
    collection do
      get 'make'
      post 'save'
    end
  end
  resources :services
  resources :clients
  resources :stylists
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  #  get 'store/index'
  # root 'day_book#index', as: 'day_book_index'


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :stylist
  belongs_to :client
  belongs_to :service
  has_many :calendar_bookings

  # testing
end

app/models/calendar_booking.rb
class CalendarBooking < ApplicationRecord
  belongs_to :booking
  belongs_to :shop_calendar
end

app/models/client.rb
class Client < ApplicationRecord
  belongs_to :stylist
  has_many :bookings
end

app/models/day_slot.rb
class ShopDayBook
  attr_accessor   :name
  attr_accessor   :day
  attr_accessor   :shop_id
  attr_accessor   :stylistdays
  attr_accessor   :shop
  def initialize (shop, day)
    @shop = shop
    @name = shop.name
    @day = day.to_s(:db)
    @shop_id = shop.id
    load_stylistdays(@day)
  end

  def load_stylistdays(day)
    @stylistdays = Array.new

    @shop.shop_stylists.each do |stylist|
      stylist_day = StylistDay.new(stylist, @day)
      @stylistdays.push(stylist_day)
    end

  end
end


class StylistDay
  attr_accessor :name
  attr_accessor :day
  attr_accessor :stylist_id
  attr_accessor :image_url
  attr_accessor :dayslots
  attr_accessor :stylist
  def initialize (stylist, day)
    @stylist = stylist
    @name = stylist.name
    @day = day.to_s
    @stylist_id = stylist_id
    @image_url = stylist.image_url
    load_slots()
  end
  def load_slots()
    start_date = DateTime.parse(@day).beginning_of_day.to_s(:db)
    end_date = DateTime.parse(@day).end_of_day.to_s(:db)
    search_str = "shop_id = "
    search_str += shop_id.to_s
    search_str += " AND stylist_id ="
    search_str += @stylist_id.to_s
    search_str += " AND slot_start >= Datetime('"
    search_str += start_date
    search_str += "') AND slot_end <= Datetime('"
    search_str += end_date + "')"
     #
    # load all the empty slots
    #
    @dayslots = Array.new
    last_id = 0
    ShopCalendar.where(search_str).find_each do |slot|
      #
      # if the slot is in the Calendar Bookings table, it means there is a booking for this slot
      #
      booking = CalendarBooking.find_by(shop_calendar_id:slot.id)
      if (booking) then
        if last_id == booking.booking_id then
          # ignore if we already created the booking slot
        else
          # create a new booking slot
          slot = CalendarSlot.new(booking.booking_id,"Booked")
          @dayslots.push(slot)
          last_id = booking.booking_id
        end
      else
        slot = CalendarSlot.new(slot.id,'Empty slot')
        @dayslots.push(slot)
      end
    end
  end
end


class CalendarSlot
  attr_accessor :slot_start
  attr_accessor :slot_id
  attr_accessor :duration
  attr_accessor :client_name
  attr_accessor :client_contact_no
  attr_accessor :client_id
  attr_accessor :service_name
  attr_accessor :slot_end
  attr_accessor :slot_type
  def initialize(slot_id, slot_type )
    @slot_type = slot_type
    @slot_id = slot_id
    if slot_type == "Empty slot" then
      slot = ShopCalendar.find(slot_id)
      @slot_start = slot.slot_start.to_s(:db)
      @duration = slot.duration
      @slot_end = slot.slot_end.to_s(:db)

    elsif slot_type == "Not Available" then


    elsif slot_type == "Booked" then
      slot = Booking.find(slot_id)
      client = slot.client
      service = slot.service
      @slot_start = slot.date.to_s(:db)
      @duration = service.duration
      @client_name = client.firstName + " " + client.lastName
      @client_contact_no = client.contactNo
      @client_id = client.id
      @service_name = service.name
      @slot_end = (slot.date + service.duration.minutes).to_s(:db)

    end


  end
end

app/models/hair_dresser.rb
class HairDresser < ApplicationRecord
  has_many :shops
end

app/models/service.rb
class Service < ApplicationRecord
  has_many :bookings
end

app/models/shop.rb
class Shop < ApplicationRecord
  belongs_to :hair_dresser
  has_many :shop_settings
  has_many :shop_workdays
  has_many :shop_calendars
  has_many :shop_stylists
  has_many :shop_stylist_workdays

end

app/models/shop_calendar.rb
class ShopCalendar < ApplicationRecord
  belongs_to :shop
  belongs_to :stylist
  has_many :calendar_bookings

end

app/models/shop_setting.rb
class ShopSetting < ApplicationRecord
  belongs_to :shop
end

app/models/shop_stylist.rb
class ShopStylist < ApplicationRecord
  belongs_to :shop
  belongs_to :stylist
end

app/models/shop_stylist_workday.rb
class ShopStylistWorkday < ApplicationRecord
  belongs_to :shop
  belongs_to :stylist
end

app/models/shop_workday.rb
class ShopWorkday < ApplicationRecord
  belongs_to :shop
end

app/models/stylist.rb
class Stylist < ApplicationRecord
  has_many :clients
  has_many :bookings
  has_many :shop_calendars
  has_many :shop_stylist_workdays
  has_many :shop_stylists

end

app/controllers/shops_controller.rb
class ShopsController < ApplicationController
  before_action :set_shop, only: [:show, :edit, :update, :destroy]

  # GET /shops
  # GET /shops.json
  def index
    @shops = Shop.all
  end

  # GET /shops/1
  # GET /shops/1.json
  def show
  end

  # GET /shops/new
  def new
    @shop = Shop.new
  end

  # GET /shops/1/edit
  def edit
  end

  # POST /shops
  # POST /shops.json
  def create
    @shop = Shop.new(shop_params)

    respond_to do |format|
      if @shop.save
        format.html { redirect_to @shop, notice: 'Shop was successfully created.' }
        format.json { render :show, status: :created, location: @shop }
      else
        format.html { render :new }
        format.json { render json: @shop.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /shops/1
  # PATCH/PUT /shops/1.json
  def update
    respond_to do |format|
      if @shop.update(shop_params)
        format.html { redirect_to @shop, notice: 'Shop was successfully updated.' }
        format.json { render :show, status: :ok, location: @shop }
      else
        format.html { render :edit }
        format.json { render json: @shop.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /shops/1
  # DELETE /shops/1.json
  def destroy
    @shop.destroy
    respond_to do |format|
      format.html { redirect_to shops_url, notice: 'Shop was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_shop
      @shop = Shop.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def shop_params
      params.require(:shop).permit(:name, :address, :contact_no, :alt_contact_no, :email, :website, :image_url, :logo_url, :theme, :main_branch, :status, :hair_dresser_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/booker_helper.rb
module BookerHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/day_book_helper.rb
module DayBookHelper
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/helpers/shops_helper.rb
module ShopsHelper
end

app/helpers/stylists_helper.rb
module StylistsHelper
end

app/views/shops/_form.html.erb
<%= form_for(shop) do |f| %>
  <% if shop.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(shop.errors.count, "error") %> prohibited this shop from being saved:</h2>

      <ul>
      <% shop.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :address %>
    <%= f.text_field :address %>
  </div>

  <div class="field">
    <%= f.label :contact_no %>
    <%= f.text_field :contact_no %>
  </div>

  <div class="field">
    <%= f.label :alt_contact_no %>
    <%= f.text_field :alt_contact_no %>
  </div>

  <div class="field">
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>

  <div class="field">
    <%= f.label :website %>
    <%= f.text_field :website %>
  </div>

  <div class="field">
    <%= f.label :image_url %>
    <%= f.text_field :image_url %>
  </div>

  <div class="field">
    <%= f.label :logo_url %>
    <%= f.text_field :logo_url %>
  </div>

  <div class="field">
    <%= f.label :theme %>
    <%= f.text_field :theme %>
  </div>

  <div class="field">
    <%= f.label :main_branch %>
    <%= f.check_box :main_branch %>
  </div>

  <div class="field">
    <%= f.label :status %>
    <%= f.text_field :status %>
  </div>

  <div class="field">
    <%= f.label :hair_dresser_id %>
    <%= f.text_field :hair_dresser_id %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/shops/edit.html.erb
<h1>Editing Shop</h1>

<%= render 'form', shop: @shop %>

<%= link_to 'Show', @shop %> |
<%= link_to 'Back', shops_path %>

app/views/shops/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Shops</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Address</th>
      <th>Contact no</th>
      <th>Alt contact no</th>
      <th>Email</th>
      <th>Website</th>
      <th>Image url</th>
      <th>Logo url</th>
      <th>Theme</th>
      <th>Main branch</th>
      <th>Status</th>
      <th>Hair dresser</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @shops.each do |shop| %>
      <tr>
        <td><%= shop.name %></td>
        <td><%= shop.address %></td>
        <td><%= shop.contact_no %></td>
        <td><%= shop.alt_contact_no %></td>
        <td><%= shop.email %></td>
        <td><%= shop.website %></td>
        <td><%= shop.image_url %></td>
        <td><%= shop.logo_url %></td>
        <td><%= shop.theme %></td>
        <td><%= shop.main_branch %></td>
        <td><%= shop.status %></td>
        <td><%= shop.hair_dresser %></td>
        <td><%= link_to 'Show', shop %></td>
        <td><%= link_to 'Edit', edit_shop_path(shop) %></td>
        <td><%= link_to 'Destroy', shop, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Shop', new_shop_path %>

app/views/shops/new.html.erb
<h1>New Shop</h1>

<%= render 'form', shop: @shop %>

<%= link_to 'Back', shops_path %>

app/views/shops/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @shop.name %>
</p>

<p>
  <strong>Address:</strong>
  <%= @shop.address %>
</p>

<p>
  <strong>Contact no:</strong>
  <%= @shop.contact_no %>
</p>

<p>
  <strong>Alt contact no:</strong>
  <%= @shop.alt_contact_no %>
</p>

<p>
  <strong>Email:</strong>
  <%= @shop.email %>
</p>

<p>
  <strong>Website:</strong>
  <%= @shop.website %>
</p>

<p>
  <strong>Image url:</strong>
  <%= @shop.image_url %>
</p>

<p>
  <strong>Logo url:</strong>
  <%= @shop.logo_url %>
</p>

<p>
  <strong>Theme:</strong>
  <%= @shop.theme %>
</p>

<p>
  <strong>Main branch:</strong>
  <%= @shop.main_branch %>
</p>

<p>
  <strong>Status:</strong>
  <%= @shop.status %>
</p>

<p>
  <strong>Hair dresser:</strong>
  <%= @shop.hair_dresser %>
</p>

<%= link_to 'Edit', edit_shop_path(@shop) %> |
<%= link_to 'Back', shops_path %>