config/routes.rb
Rails.application.routes.draw do
  get 'day_book/index'

  resources :calendar_bookings
  resources :shop_calendars
  resources :shop_stylist_workdays
  resources :shop_stylists
  resources :shop_workdays
  resources :shop_settings
  resources :shops
  resources :hair_dressers
  get 'booker/day'

  get 'booker/week'

  resources :bookings do
    collection do
      get 'make'
      post 'save'
    end
  end
  resources :services
  resources :clients
  resources :stylists
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  #  get 'store/index'
  # root 'day_book#index', as: 'day_book_index'


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :stylist
  belongs_to :client
  belongs_to :service
  has_many :calendar_bookings

  # testing
end

app/models/calendar_booking.rb
class CalendarBooking < ApplicationRecord
  belongs_to :booking
  belongs_to :shop_calendar
end

app/models/client.rb
class Client < ApplicationRecord
  belongs_to :stylist
  has_many :bookings
end

app/models/day_slot.rb
class ShopDayBook
  attr_accessor   :name
  attr_accessor   :day
  attr_accessor   :shop_id
  attr_accessor   :stylistdays
  attr_accessor   :shop
  def initialize (shop, day)
    @shop = shop
    @name = shop.name
    @day = day.to_s(:db)
    @shop_id = shop.id
    load_stylistdays(@day)
  end

  def load_stylistdays(day)
    @stylistdays = Array.new

    @shop.shop_stylists.each do |stylist|
      stylist_day = StylistDay.new(stylist, @day)
      @stylistdays.push(stylist_day)
    end

  end
end


class StylistDay
  attr_accessor :name
  attr_accessor :day
  attr_accessor :stylist_id
  attr_accessor :image_url
  attr_accessor :dayslots
  attr_accessor :stylist
  def initialize (stylist, day)
    @stylist = stylist
    @name = stylist.name
    @day = day.to_s
    @stylist_id = stylist_id
    @image_url = stylist.image_url
    load_slots()
  end
  def load_slots()
    start_date = DateTime.parse(@day).beginning_of_day.to_s(:db)
    end_date = DateTime.parse(@day).end_of_day.to_s(:db)
    search_str = "shop_id = "
    search_str += shop_id.to_s
    search_str += " AND stylist_id ="
    search_str += @stylist_id.to_s
    search_str += " AND slot_start >= Datetime('"
    search_str += start_date
    search_str += "') AND slot_end <= Datetime('"
    search_str += end_date + "')"
     #
    # load all the empty slots
    #
    @dayslots = Array.new
    last_id = 0
    ShopCalendar.where(search_str).find_each do |slot|
      #
      # if the slot is in the Calendar Bookings table, it means there is a booking for this slot
      #
      booking = CalendarBooking.find_by(shop_calendar_id:slot.id)
      if (booking) then
        if last_id == booking.booking_id then
          # ignore if we already created the booking slot
        else
          # create a new booking slot
          slot = CalendarSlot.new(booking.booking_id,"Booked")
          @dayslots.push(slot)
          last_id = booking.booking_id
        end
      else
        slot = CalendarSlot.new(slot.id,'Empty slot')
        @dayslots.push(slot)
      end
    end
  end
end


class CalendarSlot
  attr_accessor :slot_start
  attr_accessor :slot_id
  attr_accessor :duration
  attr_accessor :client_name
  attr_accessor :client_contact_no
  attr_accessor :client_id
  attr_accessor :service_name
  attr_accessor :slot_end
  attr_accessor :slot_type
  def initialize(slot_id, slot_type )
    @slot_type = slot_type
    @slot_id = slot_id
    if slot_type == "Empty slot" then
      slot = ShopCalendar.find(slot_id)
      @slot_start = slot.slot_start.to_s(:db)
      @duration = slot.duration
      @slot_end = slot.slot_end.to_s(:db)

    elsif slot_type == "Not Available" then


    elsif slot_type == "Booked" then
      slot = Booking.find(slot_id)
      client = slot.client
      service = slot.service
      @slot_start = slot.date.to_s(:db)
      @duration = service.duration
      @client_name = client.firstName + " " + client.lastName
      @client_contact_no = client.contactNo
      @client_id = client.id
      @service_name = service.name
      @slot_end = (slot.date + service.duration.minutes).to_s(:db)

    end


  end
end

app/models/hair_dresser.rb
class HairDresser < ApplicationRecord
  has_many :shops
end

app/models/service.rb
class Service < ApplicationRecord
  has_many :bookings
end

app/models/shop.rb
class Shop < ApplicationRecord
  belongs_to :hair_dresser
  has_many :shop_settings
  has_many :shop_workdays
  has_many :shop_calendars
  has_many :shop_stylists
  has_many :shop_stylist_workdays

end

app/models/shop_calendar.rb
class ShopCalendar < ApplicationRecord
  belongs_to :shop
  belongs_to :stylist
  has_many :calendar_bookings

end

app/models/shop_setting.rb
class ShopSetting < ApplicationRecord
  belongs_to :shop
end

app/models/shop_stylist.rb
class ShopStylist < ApplicationRecord
  belongs_to :shop
  belongs_to :stylist
end

app/models/shop_stylist_workday.rb
class ShopStylistWorkday < ApplicationRecord
  belongs_to :shop
  belongs_to :stylist
end

app/models/shop_workday.rb
class ShopWorkday < ApplicationRecord
  belongs_to :shop
end

app/models/stylist.rb
class Stylist < ApplicationRecord
  has_many :clients
  has_many :bookings
  has_many :shop_calendars
  has_many :shop_stylist_workdays
  has_many :shop_stylists

end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  before_action :set_client, only: [:show, :edit, :update, :destroy]

  # GET /clients
  # GET /clients.json
  def index
    @clients = Client.all
  end

  # GET /clients/1
  # GET /clients/1.json
  def show
  end

  # GET /clients/new
  def new
    @client = Client.new
  end

  # GET /clients/1/edit
  def edit
  end

  # POST /clients
  # POST /clients.json
  def create
    @client = Client.new(client_params)

    respond_to do |format|
      if @client.save
        format.html { redirect_to @client, notice: 'Client was successfully created.' }
        format.json { render :show, status: :created, location: @client }
      else
        format.html { render :new }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clients/1
  # PATCH/PUT /clients/1.json
  def update
    respond_to do |format|
      if @client.update(client_params)
        format.html { redirect_to @client, notice: 'Client was successfully updated.' }
        format.json { render :show, status: :ok, location: @client }
      else
        format.html { render :edit }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clients/1
  # DELETE /clients/1.json
  def destroy
    @client.destroy
    respond_to do |format|
      format.html { redirect_to clients_url, notice: 'Client was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_client
      @client = Client.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def client_params
      params.require(:client).permit(:firstName, :lastName, :image_url, :stylist_id, :sex, :contactNo, :email)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/booker_helper.rb
module BookerHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/day_book_helper.rb
module DayBookHelper
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/helpers/shops_helper.rb
module ShopsHelper
end

app/helpers/stylists_helper.rb
module StylistsHelper
end

app/views/clients/_form.html.erb
<%= form_for(client) do |f| %>
  <% if client.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(client.errors.count, "error") %> prohibited this client from being saved:</h2>

      <ul>
      <% client.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :firstName %>
    <%= f.text_field :firstName %>
  </div>

  <div class="field">
    <%= f.label :lastName %>
    <%= f.text_field :lastName %>
  </div>

  <div class="field">
    <%= f.label :image_url %>
    <%= f.text_field :image_url %>
  </div>

  <div class="field">
    <%= f.label :stylist_id %>
    <%= f.text_field :stylist_id %>
  </div>

  <div class="field">
    <%= f.label :sex %>
    <%= f.text_field :sex %>
  </div>

  <div class="field">
    <%= f.label :contactNo %>
    <%= f.text_field :contactNo %>
  </div>

  <div class="field">
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/clients/edit.html.erb
<h1>Editing Client</h1>

<%= render 'form', client: @client %>

<%= link_to 'Show', @client %> |
<%= link_to 'Back', clients_path %>

app/views/clients/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Clients</h1>

<table>
  <thead>
    <tr>
      <th>Firstname</th>
      <th>Lastname</th>
      <th>Image url</th>
      <th>Stylist</th>
      <th>Sex</th>
      <th>Contactno</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @clients.each do |client| %>
      <tr>
        <td><%= client.firstName %></td>
        <td><%= client.lastName %></td>
        <td><%= client.image_url %></td>
        <td><%= client.stylist %></td>
        <td><%= client.sex %></td>
        <td><%= client.contactNo %></td>
        <td><%= client.email %></td>
        <td><%= link_to 'Show', client %></td>
        <td><%= link_to 'Edit', edit_client_path(client) %></td>
        <td><%= link_to 'Destroy', client, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Client', new_client_path %>

app/views/clients/new.html.erb
<h1>New Client</h1>

<%= render 'form', client: @client %>

<%= link_to 'Back', clients_path %>

app/views/clients/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Firstname:</strong>
  <%= @client.firstName %>
</p>

<p>
  <strong>Lastname:</strong>
  <%= @client.lastName %>
</p>

<p>
  <strong>Image url:</strong>
  <%= @client.image_url %>
</p>

<p>
  <strong>Stylist:</strong>
  <%= @client.stylist %>
</p>

<p>
  <strong>Sex:</strong>
  <%= @client.sex %>
</p>

<p>
  <strong>Contactno:</strong>
  <%= @client.contactNo %>
</p>

<p>
  <strong>Email:</strong>
  <%= @client.email %>
</p>

<%= link_to 'Edit', edit_client_path(@client) %> |
<%= link_to 'Back', clients_path %>