config/routes.rb
Rails.application.routes.draw do
  get 'day_book/index'

  resources :calendar_bookings
  resources :shop_calendars
  resources :shop_stylist_workdays
  resources :shop_stylists
  resources :shop_workdays
  resources :shop_settings
  resources :shops
  resources :hair_dressers
  get 'booker/day'

  get 'booker/week'

  resources :bookings do
    collection do
      get 'make'
      post 'save'
    end
  end
  resources :services
  resources :clients
  resources :stylists
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  #  get 'store/index'
  # root 'day_book#index', as: 'day_book_index'


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :stylist
  belongs_to :client
  belongs_to :service
  has_many :calendar_bookings

  # testing
end

app/models/calendar_booking.rb
class CalendarBooking < ApplicationRecord
  belongs_to :booking
  belongs_to :shop_calendar
end

app/models/client.rb
class Client < ApplicationRecord
  belongs_to :stylist
  has_many :bookings
end

app/models/day_slot.rb
class ShopDayBook
  attr_accessor   :name
  attr_accessor   :day
  attr_accessor   :shop_id
  attr_accessor   :stylistdays
  attr_accessor   :shop
  def initialize (shop, day)
    @shop = shop
    @name = shop.name
    @day = day.to_s(:db)
    @shop_id = shop.id
    load_stylistdays(@day)
  end

  def load_stylistdays(day)
    @stylistdays = Array.new

    @shop.shop_stylists.each do |stylist|
      stylist_day = StylistDay.new(stylist, @day)
      @stylistdays.push(stylist_day)
    end

  end
end


class StylistDay
  attr_accessor :name
  attr_accessor :day
  attr_accessor :stylist_id
  attr_accessor :image_url
  attr_accessor :dayslots
  attr_accessor :stylist
  def initialize (stylist, day)
    @stylist = stylist
    @name = stylist.name
    @day = day.to_s
    @stylist_id = stylist_id
    @image_url = stylist.image_url
    load_slots()
  end
  def load_slots()
    start_date = DateTime.parse(@day).beginning_of_day.to_s(:db)
    end_date = DateTime.parse(@day).end_of_day.to_s(:db)
    search_str = "shop_id = "
    search_str += shop_id.to_s
    search_str += " AND stylist_id ="
    search_str += @stylist_id.to_s
    search_str += " AND slot_start >= Datetime('"
    search_str += start_date
    search_str += "') AND slot_end <= Datetime('"
    search_str += end_date + "')"
     #
    # load all the empty slots
    #
    @dayslots = Array.new
    last_id = 0
    ShopCalendar.where(search_str).find_each do |slot|
      #
      # if the slot is in the Calendar Bookings table, it means there is a booking for this slot
      #
      booking = CalendarBooking.find_by(shop_calendar_id:slot.id)
      if (booking) then
        if last_id == booking.booking_id then
          # ignore if we already created the booking slot
        else
          # create a new booking slot
          slot = CalendarSlot.new(booking.booking_id,"Booked")
          @dayslots.push(slot)
          last_id = booking.booking_id
        end
      else
        slot = CalendarSlot.new(slot.id,'Empty slot')
        @dayslots.push(slot)
      end
    end
  end
end


class CalendarSlot
  attr_accessor :slot_start
  attr_accessor :slot_id
  attr_accessor :duration
  attr_accessor :client_name
  attr_accessor :client_contact_no
  attr_accessor :client_id
  attr_accessor :service_name
  attr_accessor :slot_end
  attr_accessor :slot_type
  def initialize(slot_id, slot_type )
    @slot_type = slot_type
    @slot_id = slot_id
    if slot_type == "Empty slot" then
      slot = ShopCalendar.find(slot_id)
      @slot_start = slot.slot_start.to_s(:db)
      @duration = slot.duration
      @slot_end = slot.slot_end.to_s(:db)

    elsif slot_type == "Not Available" then


    elsif slot_type == "Booked" then
      slot = Booking.find(slot_id)
      client = slot.client
      service = slot.service
      @slot_start = slot.date.to_s(:db)
      @duration = service.duration
      @client_name = client.firstName + " " + client.lastName
      @client_contact_no = client.contactNo
      @client_id = client.id
      @service_name = service.name
      @slot_end = (slot.date + service.duration.minutes).to_s(:db)

    end


  end
end

app/models/hair_dresser.rb
class HairDresser < ApplicationRecord
  has_many :shops
end

app/models/service.rb
class Service < ApplicationRecord
  has_many :bookings
end

app/models/shop.rb
class Shop < ApplicationRecord
  belongs_to :hair_dresser
  has_many :shop_settings
  has_many :shop_workdays
  has_many :shop_calendars
  has_many :shop_stylists
  has_many :shop_stylist_workdays

end

app/models/shop_calendar.rb
class ShopCalendar < ApplicationRecord
  belongs_to :shop
  belongs_to :stylist
  has_many :calendar_bookings

end

app/models/shop_setting.rb
class ShopSetting < ApplicationRecord
  belongs_to :shop
end

app/models/shop_stylist.rb
class ShopStylist < ApplicationRecord
  belongs_to :shop
  belongs_to :stylist
end

app/models/shop_workday.rb
class ShopWorkday < ApplicationRecord
  belongs_to :shop
end

app/models/stylist.rb
class Stylist < ApplicationRecord
  has_many :clients
  has_many :bookings
  has_many :shop_calendars
  has_many :shop_stylist_workdays
  has_many :shop_stylists

end

app/controllers/shop_workdays_controller.rb
class ShopWorkdaysController < ApplicationController
  before_action :set_shop_workday, only: [:show, :edit, :update, :destroy]

  # GET /shop_workdays
  # GET /shop_workdays.json
  def index
    @shop_workdays = ShopWorkday.all
  end

  # GET /shop_workdays/1
  # GET /shop_workdays/1.json
  def show
  end

  # GET /shop_workdays/new
  def new
    @shop_workday = ShopWorkday.new
  end

  # GET /shop_workdays/1/edit
  def edit
  end

  # POST /shop_workdays
  # POST /shop_workdays.json
  def create
    @shop_workday = ShopWorkday.new(shop_workday_params)

    respond_to do |format|
      if @shop_workday.save
        format.html { redirect_to @shop_workday, notice: 'Shop workday was successfully created.' }
        format.json { render :show, status: :created, location: @shop_workday }
      else
        format.html { render :new }
        format.json { render json: @shop_workday.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /shop_workdays/1
  # PATCH/PUT /shop_workdays/1.json
  def update
    respond_to do |format|
      if @shop_workday.update(shop_workday_params)
        format.html { redirect_to @shop_workday, notice: 'Shop workday was successfully updated.' }
        format.json { render :show, status: :ok, location: @shop_workday }
      else
        format.html { render :edit }
        format.json { render json: @shop_workday.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /shop_workdays/1
  # DELETE /shop_workdays/1.json
  def destroy
    @shop_workday.destroy
    respond_to do |format|
      format.html { redirect_to shop_workdays_url, notice: 'Shop workday was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_shop_workday
      @shop_workday = ShopWorkday.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def shop_workday_params
      params.require(:shop_workday).permit(:shop_id, :day, :start_time, :close_time, :open)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/booker_helper.rb
module BookerHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/day_book_helper.rb
module DayBookHelper
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/helpers/shop_workdays_helper.rb
module ShopWorkdaysHelper
end

app/helpers/shops_helper.rb
module ShopsHelper
end

app/helpers/stylists_helper.rb
module StylistsHelper
end

app/views/shop_workdays/_form.html.erb
<%= form_for(shop_workday) do |f| %>
  <% if shop_workday.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(shop_workday.errors.count, "error") %> prohibited this shop_workday from being saved:</h2>

      <ul>
      <% shop_workday.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :shop_id %>
    <%= f.text_field :shop_id %>
  </div>

  <div class="field">
    <%= f.label :day %>
    <%= f.text_field :day %>
  </div>

  <div class="field">
    <%= f.label :start_time %>
    <%= f.time_select :start_time %>
  </div>

  <div class="field">
    <%= f.label :close_time %>
    <%= f.time_select :close_time %>
  </div>

  <div class="field">
    <%= f.label :open %>
    <%= f.check_box :open %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/shop_workdays/edit.html.erb
<h1>Editing Shop Workday</h1>

<%= render 'form', shop_workday: @shop_workday %>

<%= link_to 'Show', @shop_workday %> |
<%= link_to 'Back', shop_workdays_path %>

app/views/shop_workdays/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Shop Workdays</h1>

<table>
  <thead>
    <tr>
      <th>Shop</th>
      <th>Day</th>
      <th>Start time</th>
      <th>Close time</th>
      <th>Open</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @shop_workdays.each do |shop_workday| %>
      <tr>
        <td><%= shop_workday.shop %></td>
        <td><%= shop_workday.day %></td>
        <td><%= shop_workday.start_time %></td>
        <td><%= shop_workday.close_time %></td>
        <td><%= shop_workday.open %></td>
        <td><%= link_to 'Show', shop_workday %></td>
        <td><%= link_to 'Edit', edit_shop_workday_path(shop_workday) %></td>
        <td><%= link_to 'Destroy', shop_workday, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Shop Workday', new_shop_workday_path %>

app/views/shop_workdays/new.html.erb
<h1>New Shop Workday</h1>

<%= render 'form', shop_workday: @shop_workday %>

<%= link_to 'Back', shop_workdays_path %>

app/views/shop_workdays/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Shop:</strong>
  <%= @shop_workday.shop %>
</p>

<p>
  <strong>Day:</strong>
  <%= @shop_workday.day %>
</p>

<p>
  <strong>Start time:</strong>
  <%= @shop_workday.start_time %>
</p>

<p>
  <strong>Close time:</strong>
  <%= @shop_workday.close_time %>
</p>

<p>
  <strong>Open:</strong>
  <%= @shop_workday.open %>
</p>

<%= link_to 'Edit', edit_shop_workday_path(@shop_workday) %> |
<%= link_to 'Back', shop_workdays_path %>